window.industryLookUp  =  [
    { key: '18', value: 'IT - Software' },
    { key: '78', value: 'Automation' },
    { key: '6', value: 'Banking / Financial Services' },
    { key: '23', value: 'Manufacturing' },
    { key: '9', value: 'Engineering / Construction' },
    { key: '10', value: 'Education / Training' },
    { key: '20', value: 'BPO / Call Center' },
    { key: '69', value: 'Internet / E-Commerce' },
    { key: '19', value: 'IT - Hardware / Networking' },
    { key: '4', value: 'Automobile / Auto Ancillaries' },
    { key: '46', value: 'Telecom / ISP' },
    { key: '13', value: 'Medical / Healthcare' },
    { key: '1', value: 'Advertising / MR / PR / Events' },
    { key: '2', value: 'Agriculture / Dairy' },
    { key: '68', value: 'Animation' },
    { key: '54', value: 'Architecture / Interior Design' },
    { key: '55', value: 'Astrology' },
    { key: '5', value: 'Aviation / Airline' },
    { key: '72', value: 'Broking' },
    { key: '56', value: 'Cement / Building Material' },
    { key: '7', value: 'Chemical / Plastic / Rubber / Glass' },
    { key: '14', value: 'Consumer Durables / Electronics' },
    { key: '77', value: 'Cotton / Cotton Mill' },
    { key: '79', value: 'E-Learning' },
    { key: '57', value: 'Environment / Waste Management' },
    { key: '49', value: 'Export-Import / Trading' },
    { key: '74', value: 'Facility management' },
    { key: '58', value: 'Fertilizers / Pesticides' },
    { key: '11', value: 'FMCG / F&B' },
    { key: '17', value: 'Furnishings / Sanitaryware / Electricals' },
    { key: '59', value: 'Gems / Jewellery' },
    { key: '12', value: 'Gifts / Toys / Stationary' },
    { key: '8', value: 'Government Department' },
    { key: '75', value: 'Heat ventilation Air conditioning' },
    { key: '15', value: 'Hotel / Restaurant' },
    { key: '16', value: 'Industrial Design' },
    { key: '60', value: 'Insurance' },
    { key: '61', value: 'KPO / Analytics' },
    { key: '76', value: 'Leather' },
    { key: '21', value: 'Legal' },
    { key: '22', value: 'Logistics / Courier / Transportation' },
    { key: '71', value: 'MFI ( Micro Finance )' },
    { key: '24', value: 'Management Consulting / Strategy' },
    { key: '26', value: 'Matrimony' },
    { key: '27', value: 'Media / Entertainment' },
    { key: '25', value: 'Merchant Navy' },
    { key: '28', value: 'Metal / Iron / Steel' },
    { key: '29', value: 'Military / Police / Arms & Ammunition' },
    { key: '30', value: 'Mining' },
    { key: '70', value: 'NBFC ( Non Banking Financial Services )' },
    { key: '31', value: 'NGO / Social Work' },
    { key: '33', value: 'Oil & Gas / Petroleum' },
    { key: '62', value: 'Paint' },
    { key: '51', value: 'Paper / Wood' },
    { key: '32', value: 'Personal Care / Beauty' },
    { key: '63', value: 'Pharma / Biotech' },
    { key: '34', value: 'Politics' },
    { key: '64', value: 'Power / Energy' },
    { key: '35', value: 'Printing / Packaging' },
    { key: '36', value: 'Quality Certification' },
    { key: '38', value: 'Real Estate' },
    { key: '39', value: 'Recruitment Services' },
    { key: '65', value: 'Religion / Spirituality' },
    { key: '40', value: 'Retail' },
    { key: '66', value: 'Sculpture / Craft' },
    { key: '43', value: 'Security / Detective Services' },
    { key: '73', value: 'Shipping' },
    { key: '45', value: 'Sports / Fitness' },
    { key: '3', value: 'Textile / Garments / Fashion' },
    { key: '67', value: 'Travel / Tourism' },
    { key: '48', value: 'Unskilled Labor / Domestic Help' },
    { key: '50', value: 'Veterinary Science / Pet Care' }
];
